<h1>Импорт библиотек

In [3]:
import numpy as np
import matplotlib.pyplot as plt

<h1>Задача 1. Дан набор из $p$ матриц размерностью $(n, n)$ и $p$ векторов размерностью $(n, 1)$, найти сумму произведений матриц на векторы. Написать тесты для кода

In [1]:
import numpy as np

def calculate_matrix_product_sum(matrix, vector_matrix):
    product_sum = 0
    for i in range(len(matrix)):
        product = np.dot(matrix[i], vector_matrix[:, i])
        product_sum += product
    return product_sum

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector_matrix = np.array([[2, 2, 2], [3, 3, 3], [4, 4, 4]])

result = calculate_matrix_product_sum(matrix, vector_matrix)
print('сумма произведений векторной матрицы:', result)

сумма произведений векторной матрицы: 141


<h1>Задача 2. Дана матрица M, напишите функцию, которая бинаризует матрицу по некоторому threshold (то есть, все значения большие threshold становятся равными 1, иначе 0). Напишите тесты для кода

In [2]:
import numpy as np


def binary_threshold(matrix, threshold):
    binary_matrix = np.where(matrix >= threshold, 1, 0)
    return binary_matrix


# Тест
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
threshold_value = 5
binary_M = binary_threshold(M, threshold_value)
print(binary_M)

[[0 0 0]
 [0 1 1]
 [1 1 1]]


<h1>Задача 3. Напишите функцию, которая возвращает уникальные элементы из каждой строки матрицы. Напишите такую же функцию, но для столбцов. Напишите тесты для кода

In [ ]:
import numpy as np

def remove_duplicates(arr):
    unique_rows = np.unique(arr, axis=0)
    
    unique_cols = np.unique(arr, axis=1)
    
    return unique_rows, unique_cols

# Тест
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3]])

unique_rows, unique_cols = remove_duplicates(arr)
print('Unique rows:', unique_rows)
print('Unique columns:', unique_cols)

Unique rows: [[1 2 3]
 [4 5 6]]
Unique columns: [[1 2 3]
 [4 5 6]
 [1 2 3]]


<h1>Задача 4. Напишите функцию, которая заполняет матрицу с размерами $(m, n)$ случайными числами, распределенными по нормальному закону. Затем считает мат. ожидание и дисперсию для каждого из столбцов и строк, а также строит для каждой строки и столбца гистограмму значений (использовать функцию hist из модуля matplotlib.plot)

In [ ]:
import numpy as np

def fill_matrix_with_normal_distribution(rows, cols):
    matrix = np.random.randn(rows, cols)
    return matrix

# Тест
rows = 4
cols = 5
result = fill_matrix_with_normal_distribution(rows, cols)
print(result)

[[-0.5814518  -1.59605381  1.55682166 -0.52082521  0.75204682]
 [ 1.08337264 -0.40650954 -1.03875941  0.63389747 -0.53932983]
 [-0.79347409  0.22988844  1.32084121 -0.32040372  0.2719207 ]
 [ 0.13835053 -0.68200963  1.24476149  0.94951051 -0.12322133]]


<h1>Задача 5. Напишите функцию, которая заполняет матрицу $(m, n)$ в шахматном порядке заданными числами $a$ и $b$. Напишите тесты для кода

In [ ]:
def chess(m, n, a, b):
    matrix = []
    for i in range(m):
        row = []
        for j in range(n):
            if i % 2 == 0:
                if j % 2 == 0:
                    row.append(a)
                else:
                    row.append(b)
            else:
                if j % 2 == 0:
                    row.append(b)
                else:
                    row.append(a)
        matrix.append(row)
    return matrix

# Тест
m = 4
n = 5
a = 3
b = 6
result = chess(m, n, a, b)
print(result) 

[[3, 6, 3, 6, 3], [6, 3, 6, 3, 6], [3, 6, 3, 6, 3], [6, 3, 6, 3, 6]]


<h1>Задача 6. Напишите функцию, которая отрисовывает прямоугольник с заданными размерами (a, b) на изображении размера (m, n), цвет фона задайте в схеме RGB, как и цвет прямоугольника. Цвета также должны быть параметрами функции. Напишите аналогичную функцию но для овала с полуосями a и b. Напишите тесты для кода.
Примечание: уравнение эллипса (границы овала) можно записать как:
<h1>$\frac{(x-x_0)^2}{a^2}+\frac{(y-y_0)^2}{b^2}=1$

In [ ]:
from curses.textpad import rectangle


def draw_shapes(a, b, m, n, shape_color, background_color, shape_type):
    fig, ax = plt.subplots(figsize=(m/10, n/10))
    ax.set_facecolor(background_color)

    if shape_type == 'rectangle':
        shape = rectangle(((m-a)/2, (n-b)/2), a, b, linewidth=1, edgecolor='black', facecolor=shape_color)
    elif shape_type == 'ellipse':
        shape = Ellipsis((m/2, n/2), 2*a, 2*b, linewidth=1, edgecolor='black', facecolor=shape_color)

    ax.add_patch(shape)
    ax.set_xlim(0, m)
    ax.set_ylim(0, n)
    plt.gca().set_aspect('equal', adjustable='box')
    plt.show()

# Тест
shape_type = input('rectangle')
a = int(input('4'))
b = int(input('7'))
m = int(input('4'))
n = int(input('5'))
shape_color = tuple(float(x) for x in input('shape_color=(0.8, 0.2, 0.2)').split(','))
background_color = tuple(float(x) for x in input('background_color=(0.9, 0.9, 0.9)').split(','))

draw_shapes(4, 7, 4, 5, shape_color=(0.8, 0.2, 0.2), background_color=(0.9, 0.9, 0.9, shape_type))

<h1>Задача 7. Дан некий временной ряд. Для данного ряда нужно найти его: математическое ожидание, дисперсию, СКО, найти все локальные максимумы и минимумы (локальный максимум - это точка, которая больше своих соседних точек, а локальный минимум - это точка, которая меньше своих соседей), а также вычислить для данного ряда другой ряд, получаемый методом скользящего среднего с размером окна $p$.
<h1>Примечание: метод скользящего среднего подразумевает нахождение среднего из подмножетсва ряда размером $p$

In [ ]:
import numpy as np

def analyze_time_series(time_series, window_size):
    mean = np.mean(time_series)
    variance = np.var(time_series)
    std_deviation = np.std(time_series)
    moving_avg = np.convolve(time_series, np.ones(window_size)/window_size, mode='valid')
    
    local_max_indices = []
    local_min_indices = []
    
    for i in range(1, len(time_series)-1):
        if time_series[i] >= time_series[i-1] and time_series[i] >= time_series[i+1]:
            local_max_indices.append(i)
        elif time_series[i] <= time_series[i-1] and time_series[i] <= time_series[i+1]:
            local_min_indices.append(i)
    
    return mean, variance, std_deviation, local_max_indices, local_min_indices, moving_avg

# Тест
time_series = [1, 2, 3, 2, 1, 2, 3, 4, 5, 4, 3, 2]
window_size = 3
result = analyze_time_series(time_series, window_size)
print('Mean:', result[0])
print('Variance:', result[1])
print('Standard Deviation:', result[2])
print('Local Max Indices:', result[3])
print('Local Min Indices:', result[4])
print('Moving Average:', result[5])

Mean: 2.6666666666666665
Variance: 1.3888888888888886
Standard Deviation: 1.178511301977579
Local Max Indices: [2, 8]
Local Min Indices: [4]
Moving Average: [2.         2.33333333 2.         1.66666667 2.         3.
 4.         4.33333333 4.         3.        ]


<h1> Задача 8. Дан некоторый вектор с целочисленными метками классов, напишите функцию, которая выполняет one-hot-encoding для данного вектора
<h1> One-hot-encoding - представление, в котором на месте метки некоторого класса стоит 1, в остальных позициях стоит 0. Например для вектора [0, 2, 3, 0] one-hot-encoding выглядит как: [[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]

In [ ]:
def one_hot_encoding(vector):
    
    max_val = max(vector)
    encoding_length = max_val + 1
    encoding = []
    
    for element in vector:
        
        one_hot = [0] * encoding_length
        one_hot[element] = 1
        encoding.append(one_hot)
    
    return encoding

# Тест
vector = [0, 2, 3, 0]
one_hot = one_hot_encoding(vector)
print(one_hot) 

[[1, 0, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1], [1, 0, 0, 0]]
